# Generated by Django 5.2.16 on 2026-07-19 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "foundation_accounts",
            "0002_accessrestriction_sessionrecord_userprofile_and_more",
        ),
        (
            "foundation_organizations",
            "0002_address_brandsettings_department_fiscalprofile_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(default="draft", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approved_expense_reports",
                        to="foundation_accounts.membership",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_reports",
                        to="foundation_organizations.organization",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="expense_reports",
                        to="foundation_accounts.membership",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reimbursement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("paid_at", models.DateTimeField(auto_now_add=True)),
                (
                    "report",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reimbursement",
                        to="finance_expenses.expensereport",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("expense_date", models.DateField()),
                ("category", models.CharField(max_length=64)),
                ("description", models.CharField(max_length=255)),
                (
                    "amount_incl_tax",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "recoverable_vat",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("receipt_reference", models.CharField(blank=True, max_length=255)),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="finance_expenses.expensereport",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount_incl_tax__gt", 0)),
                        name="ck_expense_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("recoverable_vat__lte", models.F("amount_incl_tax"))
                        ),
                        name="ck_expense_vat_capped",
                    ),
                ],
            },
        ),
    ]
