# Generated by Django 5.2.16 on 2026-07-19 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance_billing', '0001_initial'),
        ('management_parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='management_parties.party'),
        ),
    ]
