# Generated by Django 5.2.16 on 2026-07-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance_billing", "0004_financial_immutability_triggers"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="buyer_address",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="invoice",
            name="buyer_vat_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="invoice",
            name="early_discount_terms",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="invoice",
            name="late_penalty_rate",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="recovery_indemnity",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=8, null=True
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="seller_address",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="invoice",
            name="seller_legal_form",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="invoice",
            name="seller_legal_identifier",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="invoice",
            name="seller_registry_city",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="invoice",
            name="seller_share_capital",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="invoice",
            name="seller_vat_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="invoice",
            name="vat_exemption_mention",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
