# Generated by Django 5.2.16 on 2026-07-19 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "foundation_organizations",
            "0002_address_brandsettings_department_fiscalprofile_and_more",
        ),
        ("management_parties", "0002_partyaddress"),
    ]

    operations = [
        migrations.CreateModel(
            name="LetteringGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lettering_groups",
                        to="foundation_organizations.organization",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lettering_groups",
                        to="management_parties.party",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OpenItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("direction", models.CharField(max_length=8)),
                ("source_kind", models.CharField(max_length=32)),
                ("source_id", models.CharField(max_length=64)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="open_items",
                        to="foundation_organizations.organization",
                    ),
                ),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="open_items",
                        to="management_parties.party",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Settlement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlements",
                        to="finance_subledger.letteringgroup",
                    ),
                ),
                (
                    "open_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settlements",
                        to="finance_subledger.openitem",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="letteringgroup",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="uq_lettering_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="openitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="ck_open_item_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="openitem",
            constraint=models.UniqueConstraint(
                fields=("organization", "source_kind", "source_id"),
                name="uq_open_item_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="settlement",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gt", 0)), name="ck_settlement_positive"
            ),
        ),
    ]
