# Generated by Django 5.2.16 on 2026-07-19 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation_organizations', '0002_address_brandsettings_department_fiscalprofile_and_more'),
        ('management_crm', '0001_initial'),
        ('management_parties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='party',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='management_parties.party'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='opportunity', to='management_crm.lead'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='foundation_organizations.organization'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opportunities', to='management_parties.party'),
        ),
    ]
