# Generated by Django 5.2.16 on 2026-07-19 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foundation_documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentSignature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("signer_name", models.CharField(max_length=255)),
                ("signed_content_sha256", models.CharField(max_length=64)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="signatures",
                        to="foundation_documents.documentversion",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("version", "signer_name"),
                        name="uq_document_signature_signer",
                    )
                ],
            },
        ),
    ]
