# Generated by Django 5.2.16 on 2026-07-19 00:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation_organizations', '0002_address_brandsettings_department_fiscalprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=255)),
                ('dataset_key', models.CharField(max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='foundation_organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ReportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parameters', models.JSONField(default=dict)),
                ('row_count', models.PositiveIntegerField()),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='steering_reports.report')),
            ],
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_report_org_code'),
        ),
    ]
