# Generated by Django 5.2.16 on 2026-07-19 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "foundation_organizations",
            "0002_address_brandsettings_department_fiscalprofile_and_more",
        ),
        ("management_interventions", "0001_initial"),
        ("management_parties", "0002_partyaddress"),
        ("management_projects", "0001_initial"),
        ("management_stock", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consumeditem",
            name="stock_movement",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consumed_item",
                to="management_stock.stockmovement",
            ),
        ),
        migrations.AddField(
            model_name="customersignature",
            name="intervention",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="signature",
                to="management_interventions.intervention",
            ),
        ),
        migrations.AddField(
            model_name="consumeditem",
            name="intervention",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="consumed_items",
                to="management_interventions.intervention",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_orders",
                to="foundation_organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="party",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_orders",
                to="management_parties.party",
            ),
        ),
        migrations.AddField(
            model_name="workorder",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_orders",
                to="management_projects.project",
            ),
        ),
        migrations.AddField(
            model_name="intervention",
            name="work_order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="interventions",
                to="management_interventions.workorder",
            ),
        ),
        migrations.AddConstraint(
            model_name="consumeditem",
            constraint=models.UniqueConstraint(
                fields=("intervention", "idempotency_key"),
                name="uq_consumption_idempotency",
            ),
        ),
    ]
