# Generated by Django 5.2.16 on 2026-07-19 00:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation_organizations', '0002_address_brandsettings_department_fiscalprofile_and_more'),
        ('management_parties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=32)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(default='draft', max_length=16)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('total_excl_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_incl_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('acceptance_proof', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='foundation_organizations.organization')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='management_parties.party')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='next_versions', to='management_sales.quote')),
            ],
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='management_sales.quote')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=32)),
                ('status', models.CharField(default='open', max_length=16)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('total_excl_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_incl_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='foundation_organizations.organization')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='management_parties.party')),
                ('quote', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order', to='management_sales.quote')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deliveries', to='management_sales.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=3, max_digits=6)),
                ('delivered_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='management_sales.salesorder')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='management_sales.delivery')),
                ('order_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_lines', to='management_sales.salesorderline')),
            ],
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('organization', 'number', 'version'), name='uq_quote_org_number_version'),
        ),
        migrations.AddConstraint(
            model_name='quoteline',
            constraint=models.UniqueConstraint(fields=('quote', 'position'), name='uq_quote_line_position'),
        ),
        migrations.AddConstraint(
            model_name='salesorder',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='uq_sales_order_org_number'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.UniqueConstraint(fields=('order', 'position'), name='uq_order_line_position'),
        ),
        migrations.AddConstraint(
            model_name='salesorderline',
            constraint=models.CheckConstraint(condition=models.Q(('delivered_quantity__lte', models.F('quantity'))), name='ck_order_line_delivered_lte_ordered'),
        ),
    ]
