# Generated by Django 5.2.16 on 2026-07-19 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('steering_dashboards', '0001_initial'),
        ('steering_indicators', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwidget',
            name='indicator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='widgets', to='steering_indicators.indicatordefinition'),
        ),
        migrations.AddConstraint(
            model_name='dashboardwidget',
            constraint=models.UniqueConstraint(fields=('dashboard', 'position'), name='uq_widget_dashboard_position'),
        ),
    ]
