# Generated by Django 5.2.16 on 2026-07-19 14:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance_billing", "0005_invoice_mandatory_mentions"),
        (
            "foundation_organizations",
            "0002_address_brandsettings_department_fiscalprofile_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ElectronicInvoice",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("payload", models.JSONField()),
                ("payload_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invoice",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="electronic_invoice",
                        to="finance_billing.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProviderConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("adapter_code", models.CharField(max_length=32)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="einvoicing_provider",
                        to="foundation_organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("adapter_code", models.CharField(max_length=32)),
                ("idempotency_key", models.CharField(max_length=128)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("provider_message", models.CharField(blank=True, max_length=500)),
                ("provider_status", models.CharField(blank=True, max_length=32)),
                ("transmitted_at", models.DateTimeField(auto_now_add=True)),
                ("status_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "electronic_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transmissions",
                        to="finance_einvoicing.electronicinvoice",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("electronic_invoice", "idempotency_key"),
                        name="uq_transmission_idempotency",
                    )
                ],
            },
        ),
    ]
