# Generated by Django 5.2.16 on 2026-07-19 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation_organizations', '0002_address_brandsettings_department_fiscalprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('depends_on', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='SettingDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('value_type', models.CharField(max_length=16)),
                ('default_value', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeatureAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='foundation_configuration.feature')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feature_assignments', to='foundation_organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'feature'), name='uq_feature_assignment')],
            },
        ),
        migrations.CreateModel(
            name='SettingValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='values', to='foundation_configuration.settingdefinition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setting_values', to='foundation_organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'definition'), name='uq_setting_value')],
            },
        ),
        migrations.CreateModel(
            name='VocabularyTerm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vocabulary_terms', to='foundation_organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'key'), name='uq_vocabulary_org_key')],
            },
        ),
    ]
