# Generated by Django 5.2.16 on 2026-07-19 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "foundation_organizations",
            "0002_address_brandsettings_department_fiscalprofile_and_more",
        ),
        ("management_assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "acquisition_cost",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("in_service_on", models.DateField()),
                ("useful_life_months", models.PositiveIntegerField()),
                ("status", models.CharField(default="active", max_length=16)),
                (
                    "operational_asset",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_asset",
                        to="management_assets.asset",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_assets",
                        to="foundation_organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DepreciationPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period", models.CharField(max_length=7)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("posted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depreciation_periods",
                        to="finance_fixed_assets.fixedasset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssetDisposal",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("disposed_on", models.DateField()),
                (
                    "proceeds",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "net_book_value",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "asset",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disposal",
                        to="finance_fixed_assets.fixedasset",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="fixedasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("acquisition_cost__gt", 0)),
                name="ck_asset_cost_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="depreciationperiod",
            constraint=models.UniqueConstraint(
                fields=("asset", "period"), name="uq_depreciation_asset_period"
            ),
        ),
    ]
