# Generated by Django 5.2.12 on 2026-07-18 22:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
                ('can_read', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_validate', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_assignments', to='foundation_accounts.membership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='foundation_permissions.role')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('membership', 'role'), name='uq_role_assignment_membership_role')],
            },
        ),
    ]
