# Generated by Django 5.2.16 on 2026-07-19 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_accounts', '0002_accessrestriction_sessionrecord_userprofile_and_more'),
        ('foundation_permissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataScope',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_type', models.CharField(max_length=24)),
                ('scope_ref', models.CharField(max_length=64)),
                ('role_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_scopes', to='foundation_permissions.roleassignment')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('role_assignment', 'scope_type', 'scope_ref'), name='uq_data_scope_assignment_ref')],
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to='foundation_accounts.membership')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delegations', to='foundation_permissions.role')),
                ('to_membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to='foundation_accounts.membership')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ck_delegation_dates_ordered')],
            },
        ),
        migrations.CreateModel(
            name='PolicyDecisionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=24)),
                ('allowed', models.BooleanField()),
                ('reason', models.CharField(max_length=48)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_decisions', to='foundation_accounts.membership')),
            ],
            options={
                'indexes': [models.Index(fields=['membership', 'action'], name='idx_policy_log_membership')],
            },
        ),
    ]
