# Generated by Django 5.2.16 on 2026-07-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("foundation_organizations", "0002_address_brandsettings_department_fiscalprofile_and_more"),
        ("foundation_permissions", "0002_datascope_delegation_policydecisionlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="can_manage_permissions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="delegation",
            name="scope_ref",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="delegation",
            name="scope_type",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="policydecisionlog",
            name="scope_ref",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="policydecisionlog",
            name="scope_type",
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name="policydecisionlog",
            name="target_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="policy_decisions_targeting_organization",
                to="foundation_organizations.organization",
            ),
        ),
        migrations.AddIndex(
            model_name="policydecisionlog",
            index=models.Index(fields=["target_organization", "action"], name="idx_policy_log_target_org"),
        ),
        migrations.AddConstraint(
            model_name="datascope",
            constraint=models.CheckConstraint(
                condition=models.Q(scope_type__in=["organization", "establishment", "team", "object"]),
                name="ck_data_scope_type_supported",
            ),
        ),
        migrations.AddConstraint(
            model_name="delegation",
            constraint=models.CheckConstraint(
                condition=(models.Q(scope_ref="", scope_type="") | (~models.Q(scope_type="") & ~models.Q(scope_ref=""))),
                name="ck_delegation_scope_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="delegation",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(scope_type="")
                    | models.Q(scope_type__in=["organization", "establishment", "team", "object"])
                ),
                name="ck_delegation_scope_type_supported",
            ),
        ),
    ]
