# Generated by Django 5.2.16 on 2026-07-19 00:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation_organizations', '0002_address_brandsettings_department_fiscalprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=120)),
                ('frequency', models.CharField(max_length=24)),
                ('owner', models.CharField(max_length=120)),
                ('formula_code', models.CharField(blank=True, max_length=48)),
                ('formula_version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='indicator_definitions', to='foundation_organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=16)),
                ('value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('origin', models.CharField(max_length=16)),
                ('inputs', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='steering_indicators.indicatordefinition')),
            ],
        ),
        migrations.AddConstraint(
            model_name='indicatordefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uq_indicator_org_code'),
        ),
        migrations.AddConstraint(
            model_name='indicatorvalue',
            constraint=models.UniqueConstraint(fields=('definition', 'period'), name='uq_indicator_value_period'),
        ),
    ]
