# Generated by Django 5.2.16 on 2026-07-19 14:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExportIssue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("severity", models.CharField(max_length=16)),
                ("message", models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="FECExport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("content_hash", models.CharField(max_length=64)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
