# Generated by Django 5.2.16 on 2026-07-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance_exports", "0001_initial"),
        ("finance_ledger", "0001_initial"),
        (
            "foundation_organizations",
            "0002_address_brandsettings_department_fiscalprofile_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fecexport",
            name="fiscal_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fec_exports",
                to="finance_ledger.fiscalyear",
            ),
        ),
        migrations.AddField(
            model_name="fecexport",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fec_exports",
                to="foundation_organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="exportissue",
            name="export",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="finance_exports.fecexport",
            ),
        ),
    ]
