# Generated by Django 5.2.16 on 2026-07-19 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "foundation_accounts",
            "0002_accessrestriction_sessionrecord_userprofile_and_more",
        ),
        (
            "foundation_organizations",
            "0002_address_brandsettings_department_fiscalprofile_and_more",
        ),
        ("management_projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("activity", models.CharField(max_length=64)),
                ("hourly_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("hourly_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("valid_from", models.DateField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_rates",
                        to="foundation_organizations.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "activity", "valid_from"),
                        name="uq_billing_rate_effective",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TimeEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("activity", models.CharField(max_length=64)),
                ("started_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField()),
                ("is_billable", models.BooleanField(default=True)),
                ("status", models.CharField(default="draft", max_length=16)),
                ("correction_note", models.CharField(blank=True, max_length=500)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_entries",
                        to="foundation_organizations.organization",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_entries",
                        to="management_projects.project",
                    ),
                ),
                (
                    "worker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="time_entries",
                        to="foundation_accounts.membership",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("ended_at__gt", models.F("started_at"))),
                        name="ck_time_entry_duration",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TimesheetPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="timesheet_periods",
                        to="foundation_organizations.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "starts_on", "ends_on"),
                        name="uq_timesheet_period",
                    )
                ],
            },
        ),
    ]
