# Generated by Django 5.2.16 on 2026-07-19 14:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarryForward",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("account_code", models.CharField(max_length=16)),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClosingRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("status", models.CharField(default="open", max_length=16)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("reopened_count", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ClosingTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("is_critical", models.BooleanField(default=False)),
                ("done_at", models.DateTimeField(blank=True, null=True)),
                ("evidence", models.CharField(blank=True, max_length=500)),
                ("prepared_by", models.CharField(blank=True, max_length=255)),
                ("validated_by", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
