# Generated by Django 5.2.16 on 2026-07-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance_closing", "0001_initial"),
        ("finance_ledger", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="closingrun",
            name="fiscal_year",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="closing_run",
                to="finance_ledger.fiscalyear",
            ),
        ),
        migrations.AddField(
            model_name="carryforward",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carry_forwards",
                to="finance_closing.closingrun",
            ),
        ),
        migrations.AddField(
            model_name="closingtask",
            name="run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="finance_closing.closingrun",
            ),
        ),
    ]
