# Generated by Django 5.2.16 on 2026-07-19 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "foundation_organizations",
            "0002_address_brandsettings_department_fiscalprofile_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TaxPeriod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("starts_on", models.DateField()),
                ("ends_on", models.DateField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_periods",
                        to="foundation_organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=16)),
                ("rate", models.DecimalField(decimal_places=3, max_digits=6)),
                ("valid_from", models.DateField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_rates",
                        to="foundation_organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxReturn",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("collected", models.DecimalField(decimal_places=2, max_digits=14)),
                ("deductible", models.DecimalField(decimal_places=2, max_digits=14)),
                ("net_due", models.DecimalField(decimal_places=2, max_digits=14)),
                ("status", models.CharField(default="prepared", max_length=16)),
                ("prepared_at", models.DateTimeField(auto_now_add=True)),
                (
                    "period",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="tax_return",
                        to="finance_tax.taxperiod",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaxAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("reason", models.CharField(max_length=255)),
                (
                    "tax_return",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="adjustments",
                        to="finance_tax.taxreturn",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="taxperiod",
            constraint=models.UniqueConstraint(
                fields=("organization", "starts_on", "ends_on"), name="uq_tax_period"
            ),
        ),
        migrations.AddConstraint(
            model_name="taxrate",
            constraint=models.UniqueConstraint(
                fields=("organization", "code", "valid_from"),
                name="uq_tax_rate_effective",
            ),
        ),
    ]
