# Generated by Django 5.2.16 on 2026-07-19 00:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation_organizations', '0002_address_brandsettings_department_fiscalprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='forecasts', to='foundation_organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('assumptions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('forecast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='steering_forecasts.forecast')),
            ],
        ),
        migrations.CreateModel(
            name='ForecastLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='steering_forecasts.forecastversion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='forecastversion',
            constraint=models.UniqueConstraint(fields=('forecast', 'version'), name='uq_forecast_version'),
        ),
        migrations.AddConstraint(
            model_name='forecastline',
            constraint=models.UniqueConstraint(fields=('version', 'period'), name='uq_forecast_line_period'),
        ),
    ]
