# Generated by Django 5.2.12 on 2026-07-18 22:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation_organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80)),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_definitions', to='foundation_organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_terminal', models.BooleanField(default=False)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='foundation_workflows.workflowdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=80)),
                ('object_id', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='foundation_workflows.workflowdefinition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_instances', to='foundation_organizations.organization')),
                ('requester_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_workflow_instances', to=settings.AUTH_USER_MODEL)),
                ('current_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='foundation_workflows.workflowstate')),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80)),
                ('require_separate_approver', models.BooleanField(default=False)),
                ('definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='foundation_workflows.workflowdefinition')),
                ('source_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transitions', to='foundation_workflows.workflowstate')),
                ('target_state', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transitions', to='foundation_workflows.workflowstate')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(max_length=24)),
                ('comment', models.TextField(blank=True)),
                ('idempotency_key', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='workflow_decisions', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='foundation_workflows.workflowinstance')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions', to='foundation_workflows.workflowtransition')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workflowdefinition',
            constraint=models.UniqueConstraint(fields=('organization', 'code', 'version'), name='uq_workflow_def_org_code_version'),
        ),
        migrations.AddConstraint(
            model_name='workflowstate',
            constraint=models.UniqueConstraint(fields=('definition', 'code'), name='uq_workflow_state_def_code'),
        ),
        migrations.AddConstraint(
            model_name='workflowinstance',
            constraint=models.UniqueConstraint(fields=('organization', 'object_type', 'object_id', 'definition'), name='uq_workflow_instance_object'),
        ),
        migrations.AddConstraint(
            model_name='workflowtransition',
            constraint=models.UniqueConstraint(fields=('definition', 'code'), name='uq_workflow_transition_def_code'),
        ),
        migrations.AddConstraint(
            model_name='approvaldecision',
            constraint=models.UniqueConstraint(fields=('instance', 'idempotency_key'), name='uq_approval_decision_idempotency'),
        ),
    ]
