# Generated by Django 5.2.16 on 2026-07-19 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foundation_organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address_type', models.CharField(max_length=32)),
                ('line_1', models.CharField(max_length=255)),
                ('line_2', models.CharField(blank=True, max_length=255)),
                ('postal_code', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=120)),
                ('country_code', models.CharField(max_length=2)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='foundation_organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='BrandSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255)),
                ('primary_color', models.CharField(default='#1a1a2e', max_length=7)),
                ('secondary_color', models.CharField(default='#c9a961', max_length=7)),
                ('logo_path', models.CharField(blank=True, max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='brand_settings', to='foundation_organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='foundation_organizations.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='foundation_organizations.department')),
            ],
        ),
        migrations.CreateModel(
            name='FiscalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vat_number', models.CharField(blank=True, max_length=32)),
                ('fiscal_regime', models.CharField(blank=True, max_length=64)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_profile', to='foundation_organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('legal_form', models.CharField(blank=True, max_length=80)),
                ('registration_number', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_entities', to='foundation_organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='LegalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_capital', models.CharField(blank=True, max_length=64)),
                ('registry_city', models.CharField(blank=True, max_length=120)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='legal_profile', to='foundation_organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teams', to='foundation_organizations.department')),
            ],
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uq_department_org_name'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='uq_team_department_name'),
        ),
    ]
