# Generated by Django 5.2.16 on 2026-07-19 00:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation_organizations', '0002_address_brandsettings_department_fiscalprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=16)),
                ('display_name', models.CharField(max_length=255)),
                ('normalized_name', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('merged_into', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='merged_duplicates', to='management_parties.party')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='foundation_organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PartyIdentifier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheme', models.CharField(max_length=24)),
                ('value', models.CharField(max_length=64)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='management_parties.party')),
            ],
        ),
        migrations.CreateModel(
            name='PartyRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_type', models.CharField(max_length=24)),
                ('is_active', models.BooleanField(default=True)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='management_parties.party')),
            ],
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['organization', 'normalized_name'], name='idx_party_org_norm_name'),
        ),
        migrations.AddConstraint(
            model_name='partyidentifier',
            constraint=models.UniqueConstraint(fields=('party', 'scheme', 'value'), name='uq_party_identifier'),
        ),
        migrations.AddConstraint(
            model_name='partyrole',
            constraint=models.UniqueConstraint(fields=('party', 'role_type'), name='uq_party_role_type'),
        ),
    ]
