# Generated by Django 5.2.16 on 2026-07-19 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("management_parties", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PartyAddress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("address_type", models.CharField(max_length=32)),
                ("line_1", models.CharField(max_length=255)),
                ("line_2", models.CharField(blank=True, max_length=255)),
                ("postal_code", models.CharField(max_length=16)),
                ("city", models.CharField(max_length=120)),
                ("country_code", models.CharField(max_length=2)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "party",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="management_parties.party",
                    ),
                ),
            ],
        ),
    ]
