# Generated by Django 5.2.16 on 2026-07-19 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "foundation_organizations",
            "0002_address_brandsettings_department_fiscalprofile_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="TransmissionBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("status", models.CharField(default="draft", max_length=16)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transmission_batches",
                        to="foundation_organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountantComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("author_name", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="finance_preaccounting.transmissionbatch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountingMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source_kind", models.CharField(max_length=32)),
                ("account_code", models.CharField(max_length=16)),
                ("valid_from", models.DateField()),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounting_mappings",
                        to="foundation_organizations.organization",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "source_kind", "valid_from"),
                        name="uq_mapping_effective",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PreAccountingItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("source_kind", models.CharField(max_length=32)),
                ("source_id", models.CharField(max_length=64)),
                ("account_code", models.CharField(max_length=16)),
                ("label", models.CharField(max_length=255)),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance_preaccounting.transmissionbatch",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("batch", "position"), name="uq_preaccounting_position"
                    )
                ],
            },
        ),
    ]
