# Generated by Django 5.2.16 on 2026-07-19 14:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnalyticAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="AnalyticAxis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=32)),
                ("label", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="AnalyticAllocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("percent", models.DecimalField(decimal_places=2, max_digits=6)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "analytic_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allocations",
                        to="finance_analytic.analyticaccount",
                    ),
                ),
            ],
        ),
    ]
