# Generated by Django 5.2.16 on 2026-07-19 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance_analytic", "0001_initial"),
        ("finance_ledger", "0001_initial"),
        (
            "foundation_organizations",
            "0002_address_brandsettings_department_fiscalprofile_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticallocation",
            name="line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analytic_allocations",
                to="finance_ledger.journalentryline",
            ),
        ),
        migrations.AddField(
            model_name="analyticaxis",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analytic_axes",
                to="foundation_organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="analyticaccount",
            name="axis",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="finance_analytic.analyticaxis",
            ),
        ),
        migrations.AddConstraint(
            model_name="analyticallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("percent__gt", 0), ("percent__lte", 100)),
                name="ck_allocation_percent",
            ),
        ),
        migrations.AddConstraint(
            model_name="analyticaxis",
            constraint=models.UniqueConstraint(
                fields=("organization", "code"), name="uq_analytic_axis_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="analyticaccount",
            constraint=models.UniqueConstraint(
                fields=("axis", "code"), name="uq_analytic_account_code"
            ),
        ),
    ]
