# Generated by Django 5.2.16 on 2026-07-19 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "foundation_organizations",
            "0002_address_brandsettings_department_fiscalprofile_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Control",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("frequency_days", models.PositiveIntegerField()),
                ("last_executed_on", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ControlExecution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("executed_on", models.DateField()),
                ("evidence", models.CharField(max_length=500)),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="steering_risks.control",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Risk",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=64)),
                ("owner_name", models.CharField(max_length=255)),
                ("status", models.CharField(default="open", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="risks",
                        to="foundation_organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("happened_at", models.DateTimeField()),
                ("description", models.CharField(max_length=500)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="risk_incidents",
                        to="foundation_organizations.organization",
                    ),
                ),
                (
                    "risk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents",
                        to="steering_risks.risk",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="control",
            name="risk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="controls",
                to="steering_risks.risk",
            ),
        ),
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assessed_on", models.DateField()),
                ("impact", models.PositiveSmallIntegerField()),
                ("probability", models.PositiveSmallIntegerField()),
                ("residual_impact", models.PositiveSmallIntegerField()),
                ("residual_probability", models.PositiveSmallIntegerField()),
                (
                    "risk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="steering_risks.risk",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("impact__gte", 1),
                            ("impact__lte", 5),
                            ("probability__gte", 1),
                            ("probability__lte", 5),
                        ),
                        name="ck_assessment_scale",
                    )
                ],
            },
        ),
    ]
