# Generated by Django 5.2.16 on 2026-07-19 00:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation_organizations', '0002_address_brandsettings_department_fiscalprofile_and_more'),
        ('steering_indicators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=120)),
                ('horizon', models.DateField()),
                ('status', models.CharField(default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objectives', to='foundation_organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='KeyResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='key_results', to='steering_indicators.indicatordefinition')),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_results', to='steering_objectives.objective')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('objective', 'indicator'), name='uq_key_result_indicator'), models.CheckConstraint(condition=models.Q(('target_value__gt', 0)), name='ck_key_result_target_positive')],
            },
        ),
    ]
