# Generated by Django 5.2.16 on 2026-07-19 14:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "foundation_organizations",
            "0002_address_brandsettings_department_fiscalprofile_and_more",
        ),
        ("management_scheduling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UtilizationSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("week_start", models.DateField()),
                (
                    "available_hours",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("planned_hours", models.DecimalField(decimal_places=2, max_digits=8)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="utilization_snapshots",
                        to="foundation_organizations.organization",
                    ),
                ),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="utilization_snapshots",
                        to="management_scheduling.resource",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("resource", "week_start"),
                        name="uq_utilization_resource_week",
                    )
                ],
            },
        ),
    ]
