# Generated by Django 5.2.16 on 2026-07-19 14:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("finance_payments", "0002_initial"),
        (
            "foundation_organizations",
            "0002_address_brandsettings_department_fiscalprofile_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BankStatement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("statement_date", models.DateField()),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                (
                    "closing_balance",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("import_hash", models.CharField(max_length=64)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BankTransaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("value_date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("label", models.CharField(max_length=255)),
                (
                    "statement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="finance_banking.bankstatement",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinancialAccount",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("iban", models.CharField(blank=True, max_length=34)),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="financial_accounts",
                        to="foundation_organizations.organization",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bankstatement",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="statements",
                to="finance_banking.financialaccount",
            ),
        ),
        migrations.CreateModel(
            name="TransactionMatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bank_matches",
                        to="finance_payments.payment",
                    ),
                ),
                (
                    "transaction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="matches",
                        to="finance_banking.banktransaction",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="banktransaction",
            constraint=models.UniqueConstraint(
                fields=("statement", "position"), name="uq_bank_transaction_position"
            ),
        ),
        migrations.AddConstraint(
            model_name="bankstatement",
            constraint=models.UniqueConstraint(
                fields=("account", "import_hash"), name="uq_statement_import_hash"
            ),
        ),
    ]
