# Generated by Django 5.2.12 on 2026-07-18 22:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foundation_organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SequenceCounter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=80)),
                ('period', models.CharField(max_length=16)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sequence_counters', to='foundation_organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'code', 'period'), name='uq_sequence_org_code_period')],
            },
        ),
    ]
